### ISSUE TITLE
Adding data to edge fails

### ISSUE THREAD

**Issue by xpluscal** [reaviz/reaflow#101]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When trying to supply "data" object to edge like e.g. this:
```
{
  id: '1-2',
  from: '1',
  to: '2',
  data: {
    test: "test"
  }
}
```
the following error is returned:
```
Layout Error: Error: java.lang.Error: Severe implementation error in the Json to ElkGraph importer.
```

## Expected behavior

Expected behaviour would be to be able to use the data

## Minimal reproduction of the problem with instructions
* create an edge
* add data object

## Environment

<pre><code>
Libs:
- reaflow version: 4.2.1

**Comment by xpluscal** [comment]
@amcdnl awesome!
Quick feedback: Just assigning a string to data works (my current workaround, as opposed to using an object)

**Comment by amcdnl** [comment]
So this is the code it uses to attach attributes - https://github.com/reaviz/reaflow/blob/master/src/layout/elkLayout.ts#L245-L270

The error is coming from ELKJS so i need to see why they don't like that.

**Comment by Sigkill79** [comment]
Any update on this? We're running into the same problem :)

**Comment by Sudakatux** [comment]
Created a Pull request for this https://github.com/reaviz/reaflow/pull/149

**Comment by amcdnl** [comment]
@Sudakatux - Thanks for the contributed. Its in the latest release.
