### ISSUE TITLE
Node style prop doesn't trigger render

### ISSUE THREAD

**Issue by AykutSarac** [reaviz/reaflow#156]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

```js
<Canvas
  node={(props) => (
  <CustomNode
  style={{ fill: settings.lightmode ? "#fff" : "#000" }}
    {...props}
   />
  )}
/>
```

doesn't trigger rerender.

## Expected behavior

Should force rerender and update style.

## Environment

<pre><code>
Libs:
- react version: 17.0.2
- realayers version: X.Y.Z

Browser:
- [x] Brave
 
For Tooling issues:
- Platform:  Mac
</code></pre>

**Comment by cem-gurel47** [comment]
Did you find any solution?

**Comment by AykutSarac** [comment]
> Did you find any solution?

Check out my custom node component 
https://github.com/AykutSarac/jsonvisio.com/tree/main/src/components/CustomNode

**Comment by amcdnl** [comment]
@AykutSarac - Would u mind adding this to the docs for others?
