### ISSUE TITLE
Unwanted warning: WARNING in ./node_modules/calculate-size/lib/index.js

### ISSUE THREAD

**Issue by domipieg** [reaviz/reaflow#165]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
calculate-size third party packages may ship miss-configured sourcemaps, that interrupts the build

WARNING in ./node_modules/calculate-size/lib/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in '/home/dominik/myapp/node_modules/calculate-size/lib'

## Expected behavior
npm start should run application without warning

## Minimal reproduction of the problem with instructions

* Step 1 npx create-react-app test --template typescript (webpack 5.x.x under the hood and react 18.x.x)
* Step 2 install reaflow 5.0.5
* Step 3 npm start

(also checked in ejected react application, with webpack 4.x.x and react 17.x.x - same issue)

## What is the motivation / use case for changing the behavior?
npm start should run application without warning

## Environment

<pre><code>
Libs:
- react version: 17.x.x and 18.x.x
- webpack 4.x.x and 5.x.x
- reaflow ^5.0.5

Browser:
not relevant
 
For Tooling issues:
- Node version: 16.14.0
- Platform: Linux

Others:

</code></pre>

**Comment by amcdnl** [comment]
Thanks for logging this. I believe someone raised a similar issue and opened an issue on the calculate-size repo.

**Comment by domipieg** [comment]
thanks for the information
