### ISSUE TITLE
Reason for NodeProps's properties prop to be any?

### ISSUE THREAD

**Issue by bram209** [reaviz/reaflow#172]
Is there a reason for `properties` in `NodeProps` to be `any`?
From briefly looking over the code, should this not be `NodeData`?

I can try to assign the appropriate type and make a PR, just double checking ; )
Thanks for the library, looking good so far!

**Comment by bram209** [comment]
https://github.com/reaviz/reaflow/blob/master/src/symbols/Node/Node.tsx#L59

**Comment by amcdnl** [comment]
Might be a mistake - go ahead and send a PR.
