### ISSUE TITLE
How to drag and drop a foreign object in the editor

### ISSUE THREAD

**Issue by mhmdFawzy** [reaviz/reaflow#18]

**Comment by amcdnl** [comment]
Can you explain more?

**Comment by mhmdFawzy** [comment]
In the editor story, we can drag and drop nodes with ids. can I drag and drop foreign objects or this feature isn't available yet

**Comment by amcdnl** [comment]
I don't see why you couldn't - the 'editor' doesn't really have anything to do w/ the canvas. making that native is really outside of the scope of this project right now.

closing this for now to keep things tidy.

**Comment by saahithyan** [comment]
There is not straight way to do, but there is a work around. Add a div wrapping the canvas and do all the drag and drop there. Let me know if you need an example code.

**Comment by amcdnl** [comment]
There is demo for dragging a item from the side panel to the editor: https://reaflow.dev/?path=/story/demos-editor--simple
