### ISSUE TITLE
Is there a way to add custom properties to nodes?

### ISSUE THREAD

**Issue by ASchwad** [reaviz/reaflow#19]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[X ] Other... Please describe:
</code></pre>
Is there a way to add custom properties to nodes?

## What is the motivation / use case for changing the behavior?

I have different types of nodes, which i would like to display based on their type. I have seen in one example that i could differentiate via the id - but this is not feasible in my case. By providing a type property to the node, i could style the nodes independently. Also, i need to trigger different functionality when i interact with the nodes based on their types.

**Comment by amcdnl** [comment]
Ah yes - checkout the custom elements story => https://reaflow.dev/?path=/story/demos-basic--custom-elements

**Comment by amcdnl** [comment]
Here is an example of how I do it in my app:

```
node={(node: NodeProps) => (
                <Node
                  {...node}
                  icon={<Icon />}
                  className={classNames({
                    [css.selected]: selections.includes(node.id),
                    [css.mapNode]: node.properties.data?.type === 'map',
                    [css.nodeError]: errors.find(n => n.id === node.id)
                  })}
                  onClick={onClick}
                  onKeyDown={onKeyDown}
                    />
                  }
                  onEnter={(_event, node) => setEnteredNode(node)}
                  onLeave={() => setEnteredNode(null)}
                  onRemove={(_event, node) => onNodeRemove(node)}
                />
              )}
```

**Comment by ASchwad** [comment]
Great, thanks! I might submit a PR to extend the custom-elements example to make this functionality more intuitive.

**Comment by ASchwad** [comment]
@amcdnl if you don't mind, i would like to extend the example as in the following gist: https://gist.github.com/ASchwad/3dd1e7a411148488961611cd37b41971

I tried to push a branch right away, but I am not authorized.

btw, great work with the stories. This is some great usability to get started with your library.

**Comment by amcdnl** [comment]
@ASchwad - sure go for it! And thank you! :D
