### ISSUE TITLE
Zooming using Ref doesn't work right

### ISSUE THREAD

**Issue by amcdnl** [reaviz/reaflow#22]
I can't seem to reproduce this inside the storybook but when I have the following configuration, the zoom doesn't seem to work as expected.

```
<Canvas
              ref={canvasRef}
              fit={true}
              maxZoom={0}
```

**Comment by ASchwad** [comment]
@amcdnl Any results here? Do you have a working example for me? When I am following the example in the storybook, I receive the following error: `Cannot invoke an object which is possibly 'undefined'`

**Comment by amcdnl** [comment]
Its a typescript issue, I would just do `ref?.zoom()` - I was able to get this to work.

**Comment by ASchwad** [comment]
I tried it like this: `ref.current?.centerCanvas()` and like this `ref?.current?.centerCanvas()`
Neither attempt succeeded. I will post a complete example soon.

**Comment by ASchwad** [comment]
@amcdnl any idea? This is crucial for my project since I need to programmatically change the graph after inserting nodes.

```
import { Canvas, NodeProps, EdgeProps, CanvasRef } from 'reaflow';  

  export default function InnerGraph(...){  
    const ref = useRef<CanvasRef | null>(null);  
    ....
    return(
      <Canvas
        layoutOptions={
          {
            'elk.hierarchyHandling': 'INCLUDE_CHILDREN'
          }
        }
        zoomable={true}
        pannable={true}
        fit={true}
        readonly={true}
        direction={"RIGHT"}
        nodes={nodes}
        edges={edges}
        node={(node: NodeProps) => NodeBuilder.prepareNode(...)}
        edge={(edge: EdgeProps) => EdgeBuilder.prepareEdge(...)}
        ref={ref}
        onLayoutChange={() => {
          if(ref.current != undefined){
            ref.current?.centerCanvas()
          }
        }}
      />
    )
  }
```

**Comment by ASchwad** [comment]
One way i got it to work is using `const ref = useRef<any>(null);` but there should be a cleaner way with proper type initialization 😕

**Comment by amcdnl** [comment]
So is it only type related or is there an actual bug here?

**Comment by ASchwad** [comment]
I am not sure. In my perspective it seems like a bug, because the type definition you used in the storybook works perfectly. But as soon as I use the bundled library I need to use `any` and cannot initialize the ref by using `const ref = useRef<CanvasRef | null>(null);`

**Comment by amcdnl** [comment]
I mean't functionality bug
