### ISSUE TITLE
Module '"reflow"' has no exported member 'Canvas'.

### ISSUE THREAD

**Issue by acollazomayer** [reaviz/reaflow#245]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

<img width="550" alt="Screenshot 2023-12-13 at 17 40 11" src="https://github.com/reaviz/reaflow/assets/9849229/6dea3597-04fb-4633-9dc2-e5da1cabe938">

## Expected behavior

No errors should appear in console

## Minimal reproduction of the problem with instructions
I just installed the latest version of the library

## Environment

<pre><code>
Libs:
- react version: X.Y.Z
- realayers version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by asasmith** [comment]
Should this be `import { Canvas } from 'reaflow';` instead of `import Canvas from 'reaflow';`
