### ISSUE TITLE
Draw edge to nested node from other hierarchy level

### ISSUE THREAD

**Issue by ASchwad** [reaviz/reaflow#26]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[] Other... Please describe:
</code></pre>

Is there a way to draw edges to nested nodes as in the [elk docs](https://rtsys.informatik.uni-kiel.de/elklive/examples.html?e=hierarchy%2FhierarchicalEdges)?

## Current behavior
Providing the nested node as edge target does not work - the edge will not show.

## Expected behavior
Would be best to just provide the id of the node and edges are automatically also drawn towards nested elements.

## Example
```
nodes={[
  {
    id: '1',
    text: '1'
  },
  {
    id: '2',
    text: '2'
  },
  {
    id: '2.1',
    text: '2.1',
    parent: '2'
  },
  {
    id: '3',
    text: '3'
  }
]}
edges={[
  {
    id: '1-2',
    from: '1',
    to: '2.1'
  },
  {
    id: '2-3',
    from: '2',
    to: '3'
  }
]}
```

![image](https://user-images.githubusercontent.com/33654656/101465785-a989c280-3940-11eb-9b50-fc79bed24af9.png)

## What is the motivation / use case for changing the behavior?
I would like to display nested nodes within one node and nodes from the "outside" should directly impact these nested nodes. Therefore, I need to display a direct edge towards the nested nodes.

Since we provide a `parents` (and no `children`) property, maybe we should resolve this by using the id of the nested node directly. ELKs approach is to traverse by the parents until the child is reached like `edge source -> outside.inside.n1`, but i think their approach is not feasible for us, no?

@amcdnl could you share some thoughts on this? If you think this is a good "first ticket", i will try to implement it.

**Comment by amcdnl** [comment]
Oh interesting - I've never thought about this use case until now.

Absolutely - if you would like to tackle this I'd welcome the change - fair warning though its going to be a little tricky. Here is some code spots that might help you get started:

- Layout: https://github.com/reaviz/reaflow/blob/master/src/layout/elkLayout.ts
- Top Level Edge Render: https://github.com/reaviz/reaflow/blob/master/src/Canvas.tsx#L347
- Child Level Edge Render: https://github.com/reaviz/reaflow/blob/master/src/symbols/Node/Node.tsx#L362

I'm not entirely sure how this implementation would work off the top of my head. Its possible it could "just" work w/ a few layout tweaks but I'm not sure.

I've never seen those ELK Doc demos - that would have been so helpful as I was mostly guessing attributes for the longest time! LOL

**Comment by ASchwad** [comment]
Cool, thanks for giving me some spots to start on. I will give it a try.

>I've never seen those ELK Doc demos - that would have been so helpful as I was mostly guessing attributes for the longest time! LOL

Haha, glad to share them with you! While evaluating ELK for my project, I discovered your Repo :)

**Comment by ASchwad** [comment]
After some debugging i found out, that the start and endpoint of the edge are not calculated, so i did some research at elk. 
I figured out in [another issue](https://github.com/kieler/elkjs/issues/15), that to achieve the desired behaviour we can just pass `'elk.hierarchyHandling': 'INCLUDE_CHILDREN'` into the layoutOptions of a Canvas. 
Maybe we should include an example with this prop in the stories.

Example:
The layout is not yet perfect. The edge into the nested edge has a unnecessary bezier turn instead of going directly into the node, but better than nothing for now.

![image](https://user-images.githubusercontent.com/33654656/101646722-2cda0f80-3a38-11eb-90cc-5cf77c10d4f2.png)

`<Canvas
      layoutOptions={
        {
          'elk.hierarchyHandling': 'INCLUDE_CHILDREN'
        }
      }
      nodes={[
        {
          id: '1',
          text: '1'
        },
        {
          id: '2',
        },
        {
          id: '2.1',
          parent: '2',
          text: '2.1'
        },
        {
          id: '3',
          text: '3'
        }
      ]}
      edges={[
        {
          id: '1-2.1',
          from: '1',
          to: '2.1'
        },
        {
          id: '1-3',
          from: '1',
          to: '3',
        }
      ]}
    />`

**Comment by amcdnl** [comment]
This is nice - can you add a storybook story for it?

**Comment by ASchwad** [comment]
Will do 👍 

btw, just figured out that the edge is still "behind" the node. I styled the node to have some opacity to visualize the problem. If opacity is 100%, the tip of the edge is not shown at all because of the `fill` of the node. Using the `z-index` did not help unfortunately.

![image](https://user-images.githubusercontent.com/33654656/101651579-83961800-3a3d-11eb-942e-558efb6baf36.png)

**Comment by amcdnl** [comment]
Sigh - yes there is no zindex in SVGs. They are rendered in order of dom position. If you make a storybook story w/ the example, I can try and tweak it and see if I can make it layer correctly by re-arranging some of the dom.

In the past I've done this link type thing but its not great cuz it duplicates the elements. https://github.com/reaviz/reaviz/blob/master/src/VennDiagram/VennSeries.tsx#L205-L212

**Comment by ASchwad** [comment]
> PS: It would be great to have a example of what you built there in the stories for testing and docs.

Sure, i can do that. Do you mean like the exact example i posted above? Because I am using some material-ui components, which we need to integrate into the project then.

**Comment by ASchwad** [comment]
I noticed this issue is not as simple as it initially looked like. 

Following issues arised:

- Already elaborated the issue with hidden tips of the edge behind nodes
- The additional bezier turn in the edge towards a nested node does only occur for `direction='DOWN'` or `direction='UP'`.  
- Major issue for my use case:
Edges are rendered incorrectly if there are edges pointing into a nested node AND there are also edges within the nested node towards other nested nodes.
e.g. the badly rendered edge should be between 2.1 and 2.2
![image](https://user-images.githubusercontent.com/33654656/101758858-22bc1d80-3ad9-11eb-8af2-932ba7c10bdd.png)
`<Canvas
      layoutOptions={
        {
          'elk.hierarchyHandling': 'INCLUDE_CHILDREN'
        }
      }
      direction='RIGHT'
      nodes={[
        {
          id: '1',
          text: '1'
        },
        {
          id: '2',
        },
        {
          id: '2.1',
          parent: '2',
          text: '2.1'
        },
        {
          id: '2.2',
          parent: '2',
          text: '2.2'
        },
        {
          id: '3',
          text: '3'
        }
      ]}
      edges={[
        {
          id: '1-2.1',
          from: '1',
          to: '2.1'
        },
        {
          id: '2.1-2.2',
          from: '2.1',
          to: '2.2'
        },
        {
          id: '2.2-3',
          from: '2.2',
          to: '3'
        },
      ]}
    />`

@amcdnl maybe we should split these concerns into separate issues to handle them individually. As said, for me it is crucial to fix the last issue.

**Comment by amcdnl** [comment]
1) The Left-to-right layout needs some TLC w/ alignment of things. I think I have a issue for alignment but it doesn't call this out directly. We should make a ticket calling out the specific issues.
2) Ah good catch - I didn't even think about that. That was kind of a hack I took from react-flow and has some other issues too - there is a ticket for some alignment issues but we should make a separate ticket for this issue.
3) In your example, I think you need to include the parent on that edge.

**Comment by ASchwad** [comment]
@amcdnl thank you so much! 🎉  I did not notice so far, that edges have a parent property as well. 

So I will extract the other two problems into separate issues and create a storybook story for my example from above - then we can close this issue.

**Comment by ASchwad** [comment]
Created these issues: #31 #32
