### ISSUE TITLE
Add adjustable padding for nested nodes

### ISSUE THREAD

**Issue by ASchwad** [reaviz/reaflow#28]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, nested nodes will have default padding of 50px for all sides
`'elk.padding': '[left=50, top=50, right=50, bottom=50]',`

## Expected behavior
I have some custom node contents and nested nodes are rendered on top of the contents. Currently, I cannot adjust the position of the nested nodes dynamically and therefore I would like to set the padding within the nodeProps.

I will create a PR for this soon, just wanted to have a corresponding ticket.

**Comment by amcdnl** [comment]
You can pass in custom options - https://github.com/reaviz/reaflow/blob/master/stories/Layouts.stories.tsx#L115

**Comment by ASchwad** [comment]
That's right. In my example I want to provide a padding based on the type of the node. Therefore providing an overall padding to the canvas and hence to every node the same padding is not sufficient for my use case.
