### ISSUE TITLE
Links in code of a storybook story contains "random" links

### ISSUE THREAD

**Issue by ASchwad** [reaviz/reaflow#35]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
In the code section of stories, there are links to other stories, which not really make sense to me. So if I inspect code and want to copy it, the links are kind of annoying. 

## Expected behavior
The code of a story should not link into other stories.

## Minimal reproduction of the problem with instructions
1. Navigate to https://reaflow.dev/?path=/story/demos-nested--nested-edges
2. Checkout the code and see links into other stories

![grafik](https://user-images.githubusercontent.com/33654656/102692788-fcebf280-4215-11eb-9b94-0fac803fb84d.png)

I wrote this story in the documentation myself and this behaviour seems to come from storybook - not from the actual story code.

**Comment by amcdnl** [comment]
Hmmm - I believe this is the story plugin showing all stories for that file. Can you log a bug on the storybook repo instead?
