### ISSUE TITLE
Adding a Node between two nodes in group doesn't work as expected

### ISSUE THREAD

**Issue by VHalushko** [reaviz/reaflow#37]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior

[`upsertNode`](https://github.com/reaviz/reaflow/blob/master/src/helpers/crudHelpers.ts#L6) method doesn't use `parent` property from first edge when creating new edges, so when you add a Node between the other nodes with a parent - edges disappear from the parent node which is confusing.

## Expected behavior

Node adds and edges are updated according to the siblings

## Minimal reproduction of the problem with instructions
[StackBlitz reproduction](https://stackblitz.com/edit/react-ts-aqpgaw?file=Diagram.tsx)

* Step 1
Click on plus icon to see the results

## Environment

<pre><code>
Libs:
- react version: 17.0.1
- reaflow version: 2.6.3

Browser:
- [x] Edge version 87.0.664.75 (Official build) (64-bit)

**Comment by VHalushko** [comment]
@amcdnl Great library overall, I like it a lot!
I can create a PR with fix if you don't have any objections.

**Comment by amcdnl** [comment]
Thanks - Yes that would be appreciated!

**Comment by VHalushko** [comment]
Found one more issue with that method - it's adding edges to the end of an array instead of the place it was previously. So if you have two edges coming from one node and you try to add a node to left one - it swaps the branches and left branch becomes right. Do I add the fix to my PR, @amcdnl?

**Comment by amcdnl** [comment]
Oh interesting! I didn't think about that. Ya that would be great.
