### ISSUE TITLE
Wrong import for types in useSelection

### ISSUE THREAD

**Issue by KamalAman** [reaviz/reaflow#39]
https://github.com/reaviz/reaflow/blob/b399e01188505bdd666abd562079dcb18f9d9a1f/src/helpers/useSelection.ts#L3

You're importing `import { EdgeData, NodeData } from 'types';`

Node thinks you're trying to import a module named types instead of types file on your root.

**Comment by amcdnl** [comment]
Thanks! Resolved in 2.6.4
