### ISSUE TITLE
`setEdges` is undefined on Storybook demo

### ISSUE THREAD

**Issue by Vadorequest** [reaviz/reaflow#42]
https://reaflow.dev/?path=/story/docs-getting-started-linking-nodes--page

![image](https://user-images.githubusercontent.com/3807458/106744150-aa2c9580-661f-11eb-9b17-f0a5a09f830f.png)

Uses a `setEdges` function which isn't defined anywhere.

**Comment by amcdnl** [comment]
Ya - the code is meant to be more of psuedo code but I will fix it to be more clear.

**Comment by Vadorequest** [comment]
I think adding some comment above the function like "coming from `useState` or similar would be enough.

Or add a more complete example such as:
```
  const [nodes, setNodes] = useState<NodeData[]>([
    {
      id: '2',
      text: 'Mother',
      data: {
        gender: 'female',
      },
    },
    {
      id: '3',
      text: 'Daughter',
      data: {
        gender: 'female',
      },
    },
    {
      id: '4',
      text: 'Son',
      data: {
        gender: 'male',
      },
    },
  ]);
  const [edges, setEdges] = useState<EdgeData[]>([
    {
      id: '2-3',
      from: '2',
      to: '3',
    },
    {
      id: '2-4',
      from: '2',
      to: '4',
    },
  ]);
```

**Comment by amcdnl** [comment]
Care to make a PR to add this?

**Comment by Vadorequest** [comment]
Documentation updated in https://github.com/reaviz/reaflow/pull/72
