### ISSUE TITLE
How to persist/share the `canvasRef` to child components using a (Recoil) store?

### ISSUE THREAD

**Issue by Vadorequest** [reaviz/reaflow#49]
The documentation at https://reaflow.dev/?path=/story/docs-advanced-refs--page explains a bit how to use the `canvasRef`, but the example is very light and isn't necessarily what a real app would do.

```ts
export const MyCanvas: FC = () => {
  const ref = useRef<CanvasRef | null>(null);

  useEffect(() => {
    // Refs give you ability to do things like:
    // ref.current?.centerCanvas()
  }, [ref]);

  return <Canvas ref={ref} />;
};
```

More specifically, how can I access the `canvasRef` from a component? (Node, Edge, etc.)

I tried to store it in a shared state, but it didn't work out.

```ts
type Props = {
  canvasRef: MutableRefObject<CanvasRef | null>;
}

const CanvasContainer: React.FunctionComponent<Props> = (props): JSX.Element | null => {
  const {
    canvasRef,
  } = props;
  const [persistedCanvasRef, setPersistedCanvasRef] = useRecoilState(canvasRefState);

  useEffect(() => {
    console.log('Persisting canvas ref', canvasRef);
    setPersistedCanvasRef(canvasRef as MutableRefObject<CanvasRef>);
  }, [canvasRef]);

  ...

  return (<Canvas ... />)
}
```

Calling `setPersistedCanvasRef(canvasRef as MutableRefObject<CanvasRef>);` throws the error `TypeError: Cannot assign to read only property 'current' of object '#<Object>'`.

```ts
import { MutableRefObject } from 'react';
import { CanvasRef } from 'reaflow';
import { atom } from 'recoil';

export const canvasRefState = atom<MutableRefObject<CanvasRef> | null>({
  key: 'canvasRefState',
  default: null,
});

```

I thought I could store the canvasRef and allow any component to subscribe to it to access its properties, but it seems I misunderstood something.

Another alternative I see is to pass down the `canvasRef` as props for `Node` and `Edge` components, but that's a bit ugly/heavy.

How would you recommended doing that?

**Comment by amcdnl** [comment]
Let's move this to discussions if you don't mind.

**Comment by Vadorequest** [comment]
Moved to https://github.com/reaviz/reaflow/discussions/57
