### ISSUE TITLE
Using `autofocus=true` in textarea within `foreignObject` causes the viewport to jump when there are many nodes

### ISSUE THREAD

**Issue by Vadorequest** [reaviz/reaflow#61]
## I'm submitting a...
[x] Bug report 

## Current behavior
https://youtu.be/CtXphmb_Nkk

I'm trying to use `autofocus={true}` in a `textarea`. It works fine at the beginning, but when there are too many nodes created then the viewport jumps back to the left (maybe it tries to center the viewport?)

I'm not sure what's causing this, seems to happen when the input that is being autofocused isn't visible in the viewport.

## Expected behavior
It should center the viewport onto the newly created element.

Or maybe I could force centering the right element? 

## version
Reaflow 3.0.8

**Comment by amcdnl** [comment]
You likely need to handle focus manually. Its not uncommon. This isn't really related to this project so closing.
