### ISSUE TITLE
Edges/Ports should support `children` property (similar to Nodes)

### ISSUE THREAD

**Issue by Vadorequest** [reaviz/reaflow#67]
Currently, the Edge component doesn't support the `children` property. (or, actually, it does, but does nothing with it)

I think the Edge `children` should behave similarly to the Nodes, and accept either a component or a function that returns a react component.

I can make a PR for this.

**Comment by amcdnl** [comment]
Whats the use case for this? Doesn't make sense to me.

**Comment by Vadorequest** [comment]
Allowing the use of `foreignObject` as `children`, and draw custom HTML elements such as additional buttons of a different style to replace the built-in Add/Remove components (and other options)

I intend to use it to build my own Add/Remove buttons on edges, with actual HTML/CSS instead of SVG.

**Comment by Vadorequest** [comment]
The same logic applies to ports as well.

I need to display an icon/text next to each port. 
For instance, it would be a warning when a port isn't connected with any other node.

I think the same PR should bring support for `children` in both Ports and Edges.
