### ISSUE TITLE
`framer-motion` dependency duplicated in both `dependencies` and `devDependencies`

### ISSUE THREAD

**Issue by Vadorequest** [reaviz/reaflow#70]
`framer-motion` is listed in both. It shouldn't.

![image](https://user-images.githubusercontent.com/3807458/109066979-31849a80-76ee-11eb-8c5d-d85402c3be9c.png)

Maybe it should be listed as peerDependency?

Also, why are `react` and `react-dom` listed in `devDependencies`? Shouldn't they be listed in `dependencies` instead? (they're peer-dependencies, but aren't optional)

My understanding of `peerDependencies` might be lacking, but I feel something isn't right there.

Version: 3.0.13

**Comment by amcdnl** [comment]
Ah it was a mistake.

I had it as a peer dep before but it caused other issues so I moved it back to deps.

**Comment by Vadorequest** [comment]
Alright I'll make a PR for this then, it's small so I'll likely fix it in an existing PR.
