### ISSUE TITLE
Drag-based panning (and scroll based zoom)

### ISSUE THREAD

**Issue by C0DK** [reaviz/reaflow#78]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
To the best of my knowledge, your module was inspired by reactflow. It has a very nice control-system where you move around by dragging and then zoom by scrolling. Your example of for scrolling has a button on the right, and expects you to use the mousewheel to move. IMO not the best

## Expected behavior
I'd love to have an example on your story book, that has controls like the one in reactflow. Just inspiration on how to implement mousewheel zoom and drag-based scrolling, if possible. I'll have to try my best myself, and can provide an example of how i make it work, but it'd be nice (for future users) do have an example

## What is the motivation / use case for changing the behavior?
Better usability and more versatility.

**Comment by amcdnl** [comment]
@C0DK -

re: react-flow - not really this was a internal project for about a year and half that i recently open-sourced.

I personally disagree - that style of panning is best for 'infinite' canvases such as google maps - almost every editor based solution ( figma / sketch / etc ) use scrollbar based panning. 

This has already been raised and I don't have any intention of building this myself ( its a pain in the butt w/ the zoom/etc ), however, if someone wanted to make a PR i would accept it.

**Comment by C0DK** [comment]
Good point :) I'll use the zooming as done in the docs. thanks for the quick feedback

**Comment by amcdnl** [comment]
I think we can close this at this point - feel free to comment and reopen otherwise.
