### ISSUE TITLE
Deeply nested edges crash (but not in elkjs)

### ISSUE THREAD

**Issue by C0DK** [reaviz/reaflow#80]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Reaflow crashes (in elkjs?) when you do deeply nested edges. I've created a runnable example in this commit https://github.com/C0DK/reaflow/commit/e7d801f4ff5319925e7d2be27c71c3dba31b931b 

I thought the error was straight in elkjs, but now i'm less sure. The issue i raised at their framework can be found here https://github.com/kieler/elkjs/issues/129

## Expected behavior
It to render a graph like this:
![image](https://user-images.githubusercontent.com/9048078/112593788-4b59f000-8e08-11eb-8d4b-38883b7b4eee.png)

## Minimal reproduction of the problem with instructions

1) clone https://github.com/C0DK/reaflow/tree/error-state
2) run the storybook example
3) go to http://192.168.1.249:9009/?path=/story/demos-nested--nested-edges

## Environment

<pre><code>
Libs:
    "reaflow": "^3.0.14",
    "react": "^17.0.1",

**Comment by C0DK** [comment]
I found the root course:
https://github.com/kieler/elkjs/issues/129#issuecomment-807993296

I've also fixed it (in the branch i mention above, so if you want to reproduce it, please checkout the specific commit)

This is how i solved it for now in the story :)
https://github.com/C0DK/reaflow/commit/9c11a8c301fce42f7b171cb72f9bb52748c037e4

**Comment by amcdnl** [comment]
Can you make a PR?

**Comment by C0DK** [comment]
This is solved by the PR in my opinion - can i close it?
