### ISSUE TITLE
Feature request: disable animation on load

### ISSUE THREAD

**Issue by bguthrie** [reaviz/reaflow#82]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Currently, the on each render the diagram animates as it loads. This is a cool effect, but quickly gets distracting if a user is switching between pages rapidly, or if the app wants to render a modal-like overlay that may trigger a re-render.

I tried following down the path to the elk docs. As best I can make out, the closest parameter that might modify this behavior is `elk.animate`, which accepts a boolean, but as far as I can tell no value I could pass would alter this behavior—I tried passing a string with various values, and overriding the TS types to force an actual boolean value, without luck. I don't know where the behavior originates.

## Expected behavior
Ideally I'd like to be able to pass in a rendering option to the canvas that disables the initial animation on render.

## Minimal reproduction of the problem with instructions

N/A

## What is the motivation / use case for changing the behavior?

Non-visible root rerenders of the diagram for cases where loading behavior would otherwise make it seem distracting.

## Environment

<pre><code>
Libs:
- react version: 17.0.1
- reaflow version: 3.0.14

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by amcdnl** [comment]
I like this - been considering doing this. Its pretty easy to do - i do this a lot in my reaviz project. Just need to wire it up here.

**Comment by bguthrie** [comment]
Thanks! Let me know if I can be of help in any way—if you can point me to the right spot I'd be glad to submit a PR. Thanks for your work on the library—the result is pretty stunning.

**Comment by amcdnl** [comment]
OK - so let's just add a new property on the Canvas component called `animated` - default it to true and then in the spots where framer-motion is used u need to pass it as a flag like i did here in reaviz: https://github.com/reaviz/reaviz/blob/master/src/BarChart/BarSeries/Bar.tsx#L476

**Comment by amcdnl** [comment]
Done! 3.1.1

**Comment by bguthrie** [comment]
Oh goodness! So sorry for dawdling on this and thanks for adding it, I appreciate it.
